# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Gazetteer-FallingRain
version:      0.14
version_from: FallingRain.pm
installdirs:  site
requires:
    LWP::UserAgent:                0.01
    Test::Simple:                  0.01
    WWW::Gazetteer:                0.23

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
